micronaut:
  application:
    name: logging-service
    instance:
      id: ${random.shortuuid}
  server:
    port: -1

consul:
  client:
    registration:
      enabled: true
      check:
        http: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"

