micronaut:
  application:
    name: facade-service
consul:
  client:
    defaultZone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
    registration:
      check:
        http: true
      enabled: true